# Generated by Django 2.2.14 on 2021-06-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('coachname', models.CharField(blank=True, db_column='Coachname', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('contactnum', models.BigIntegerField(blank=True, db_column='contactNum', null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('employeedtime', models.DateTimeField(blank=True, db_column='employeedTime', null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('speciality', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'coach',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('customername', models.CharField(db_column='Customername', max_length=10, unique=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('contactnum', models.BigIntegerField(blank=True, db_column='contactNum', null=True)),
                ('registertime', models.DateTimeField(blank=True, db_column='registerTime', null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('membership', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('equipname', models.CharField(blank=True, db_column='Equipname', max_length=10, null=True)),
                ('equipdata', models.BinaryField(blank=True, db_column='EquipData', null=True)),
                ('equipextn', models.CharField(blank=True, db_column='Equipextn', max_length=10, null=True)),
                ('purchasedtime', models.DateField(blank=True, db_column='purchasedTime', null=True)),
                ('lastfix', models.CharField(blank=True, db_column='lastFix', max_length=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'equipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('managername', models.CharField(blank=True, db_column='Managername', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('contactnum', models.BigIntegerField(blank=True, db_column='contactNum', null=True)),
                ('maddress', models.CharField(blank=True, db_column='Maddress', max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('employeedtime', models.DateTimeField(blank=True, db_column='employeedTime', null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('contactnum', models.BigIntegerField(blank=True, db_column='contactNum', null=True)),
                ('taddress', models.CharField(blank=True, db_column='Taddress', max_length=30, null=True)),
                ('employeedtime', models.DateTimeField(blank=True, db_column='employeedTime', null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'Technician',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vipcard',
            fields=[
                ('cardno', models.CharField(db_column='cardNO', max_length=10, primary_key=True, serialize=False)),
                ('registertime', models.DateField(blank=True, db_column='registerTime', null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('times', models.IntegerField(blank=True, null=True)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('holder', models.ForeignKey(blank=True, db_column='holder', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Customer')),
            ],
            options={
                'db_table': 'VIPcard',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('ordinalnum', models.CharField(db_column='ordinalNum', max_length=10, primary_key=True, serialize=False)),
                ('fixday', models.DateField(blank=True, db_column='fixDay', null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('equipid', models.ForeignKey(blank=True, db_column='equipID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Equipment')),
                ('repairman', models.ForeignKey(blank=True, db_column='repairman', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Technician')),
            ],
            options={
                'db_table': 'maintenance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('classtype', models.CharField(blank=True, db_column='classType', max_length=10, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('coach', models.ForeignKey(blank=True, db_column='coach', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Coach')),
            ],
            options={
                'db_table': 'class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('contactnum', models.BigIntegerField(blank=True, db_column='contactNum', null=True)),
                ('classtime', models.CharField(blank=True, db_column='classTime', max_length=10, null=True)),
                ('classstart', models.DateTimeField(blank=True, db_column='classStart', null=True)),
                ('classleft', models.IntegerField(blank=True, db_column='classLeft', null=True)),
                ('classid', models.ForeignKey(db_column='classID', on_delete=django.db.models.deletion.DO_NOTHING,default=1, to='api.Class')),
                ('coach', models.ForeignKey(blank=True, db_column='coach', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Coach')),
            ],
            options={
                'db_table': 'student',
                'managed': True,
                'unique_together': {('id', 'classid')},
            },
        ),
        migrations.CreateModel(
            name='Classhistory',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('coachid', models.ForeignKey(db_column='coachID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, default=1,serialize=False, to='api.Coach')),
                ('classtime', models.DateField(blank=True, null=True)),
                ('classid', models.ForeignKey(db_column='classID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Class')),
                ('studentid', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Student')),
            ],
            options={
                'db_table': 'classHistory',
                'managed': True,
                'unique_together': {('coachid', 'studentid', 'classid')},
            },
        ),
    ]
