# Generated by Django 2.2.14 on 2021-06-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='ordinalnum',
        ),
        migrations.RemoveField(
            model_name='vipcard',
            name='cardno',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='classStart',
            field=models.DateTimeField(blank=True, db_column='classTime', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='coachid',
            field=models.ForeignKey(db_column='coachid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Coach'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='speciality',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vipcard',
            name='id',
            field=models.BigAutoField(db_column='ID', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='coach',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classhistory',
            name='classid',
            field=models.ForeignKey(db_column='classid', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Class'),
        ),
        migrations.AlterField(
            model_name='classhistory',
            name='coachid',
            field=models.ForeignKey(db_column='coachid', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Coach'),
        ),
        migrations.AlterField(
            model_name='classhistory',
            name='id',
            field=models.BigAutoField(db_column='ID', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classhistory',
            name='studentid',
            field=models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Student'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='classid',
            field=models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technician',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('id', 'customername')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='class',
            table='_class',
        ),
        migrations.AlterModelTable(
            name='classhistory',
            table='_classHistory',
        ),
        migrations.AlterModelTable(
            name='coach',
            table='_coach',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='_customer',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='_equipment',
        ),
        migrations.AlterModelTable(
            name='maintenance',
            table='_maintenance',
        ),
        migrations.AlterModelTable(
            name='manager',
            table='_manager',
        ),
        migrations.AlterModelTable(
            name='student',
            table='_student',
        ),
        migrations.AlterModelTable(
            name='technician',
            table='_Technician',
        ),
        migrations.AlterModelTable(
            name='vipcard',
            table='_VIPcard',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classleft',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classstart',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classtime',
        ),
        migrations.RemoveField(
            model_name='student',
            name='coach',
        ),
    ]
