# Generated by Django 2.2.14 on 2021-06-09 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210609_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classhistory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='ordinalNum',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='id',
            field=models.BigAutoField(db_column='ID', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='classleft',
            field=models.IntegerField(blank=True, db_column='classLeft', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='classstart',
            field=models.DateTimeField(blank=True, db_column='classStart', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='classtime',
            field=models.CharField(blank=True, db_column='classTime', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='coach',
            field=models.ForeignKey(blank=True, db_column='coach', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Coach'),
        ),
        migrations.AlterField(
            model_name='classhistory',
            name='classid',
            field=models.BigIntegerField(db_column='classID'),
        ),
        migrations.AlterField(
            model_name='classhistory',
            name='coachid',
            field=models.ForeignKey(db_column='coachID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Coach'),
        ),
        migrations.AlterField(
            model_name='classhistory',
            name='studentid',
            field=models.BigIntegerField(db_column='studentID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classid',
            field=models.ForeignKey(db_column='classID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Class'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('id', 'classid')},
        ),
        migrations.AlterModelTable(
            name='class',
            table='class',
        ),
        migrations.AlterModelTable(
            name='classhistory',
            table='classHistory',
        ),
        migrations.AlterModelTable(
            name='coach',
            table='coach',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='equipment',
        ),
        migrations.AlterModelTable(
            name='maintenance',
            table='maintenance',
        ),
        migrations.AlterModelTable(
            name='manager',
            table='manager',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AlterModelTable(
            name='technician',
            table='Technician',
        ),
        migrations.AlterModelTable(
            name='vipcard',
            table='VIPcard',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classStart',
        ),
        migrations.RemoveField(
            model_name='student',
            name='coachid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='student',
            name='speciality',
        ),
    ]
