# Generated by Django 2.2.14 on 2021-06-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('classtype', models.CharField(blank=True, db_column='classType', max_length=10, null=True)),
                ('coach', models.CharField(blank=True, max_length=10, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('coachname', models.CharField(blank=True, db_column='Coachname', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('contactnum', models.BigIntegerField(blank=True, db_column='contactNum', null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('employeedtime', models.DateTimeField(blank=True, db_column='employeedTime', null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('speciality', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'coach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('customername', models.CharField(db_column='Customername', max_length=10, unique=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('contactnum', models.BigIntegerField(blank=True, db_column='contactNum', null=True)),
                ('registertime', models.DateTimeField(blank=True, db_column='registerTime', null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('membership', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('equipname', models.CharField(blank=True, db_column='Equipname', max_length=10, null=True)),
                ('equipdata', models.BinaryField(blank=True, db_column='EquipData', null=True)),
                ('equipextn', models.CharField(blank=True, db_column='Equipextn', max_length=10, null=True)),
                ('purchasedtime', models.DateField(blank=True, db_column='purchasedTime', null=True)),
                ('lastfix', models.CharField(blank=True, db_column='lastFix', max_length=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fixday', models.DateField(blank=True, db_column='fixDay', null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'maintenance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('managername', models.CharField(blank=True, db_column='Managername', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('contactnum', models.BigIntegerField(blank=True, db_column='contactNum', null=True)),
                ('maddress', models.CharField(blank=True, db_column='Maddress', max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('employeedtime', models.DateTimeField(blank=True, db_column='employeedTime', null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('contactnum', models.BigIntegerField(blank=True, db_column='contactNum', null=True)),
                ('classtime', models.CharField(blank=True, db_column='classTime', max_length=10, null=True)),
                ('classstart', models.DateTimeField(blank=True, db_column='classStart', null=True)),
                ('classleft', models.IntegerField(blank=True, db_column='classLeft', null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('contactnum', models.BigIntegerField(blank=True, db_column='contactNum', null=True)),
                ('taddress', models.CharField(blank=True, db_column='Taddress', max_length=30, null=True)),
                ('employeedtime', models.DateTimeField(blank=True, db_column='employeedTime', null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'Technician',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vipcard',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('registertime', models.DateField(blank=True, db_column='registerTime', null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('times', models.IntegerField(blank=True, null=True)),
                ('deposit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VIPcard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classhistory',
            fields=[
                ('coachid', models.ForeignKey(db_column='coachID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Coach')),
                ('studentid', models.BigIntegerField(db_column='studentID')),
                ('classid', models.BigIntegerField(db_column='classID')),
                ('classtime', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classHistory',
                'managed': False,
            },
        ),
    ]
